[book]
authors = ["Project Liberty Labs"]
language = "en"
multilingual = false
src = "src"
title = "Sign In With Frequency"

[preprocessor.button-links]
command = "node preprocessors/button-links.mjs"

[preprocessor.svg-embed]
command = "node preprocessors/svg-embed.mjs"

[preprocessor.generator]
command = "node preprocessors/generator.mjs"


[output.html]
no-section-label = true
git-repository-url = "https://github.com/ProjectLibertyLabs/siwf"
edit-url-template = "https://github.com/ProjectLibertyLabs/siwf/blob/main/docs/{path}"
preferred-dark-theme = "coal"
additional-css = [
  "css/highlight.css",
  "css/highlight-dark.css",
  "css/tailwind-short.css",
  "css/button-links.css",
  "css/generator.css",
  "css/overrides.css",
]

[output.html.fold]
enable = true
