# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to GitHub Pages

on:
  push:
    branches: ['main', 'v1', 'chore/split-for-v1']
env:
  TARGET_FOLDER: ${{ github.ref == 'refs/heads/main' && 'v2' || 'v1' }}

permissions:
  contents: write

jobs:
  build_site:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build v1
        env:
          BASE_PATH_UI: /siwf/v1/ui
          BASE_PATH_EXAMPLE: /siwf/v1/example
        run: pnpm run build

      - name: Structure v1
        run: |
          mkdir siwf
          touch siwf/.nojekyll
          mkdir siwf/v1
          mkdir siwf/v1/example
          mkdir siwf/v1/ui
          mv ./packages/ui/build/* ./siwf/v1/ui
          mv ./packages/example/build/* ./siwf/v1/example

      # Should be able to move to this once the root is different
      # - name: Deploy to GitHub Pages ${{ env.TARGET_FOLDER }}
      #   uses: JamesIves/github-pages-deploy-action@v4.6.4
      #   with:
      #     branch: gh-pages
      #     folder: siwf
      #     target-folder: ${{ env.TARGET_FOLDER }} # This is what deploys us to a v1 or v2 directory
      #     clean: false # Don't clean up the other release folders

      - name: Build Root
        env:
          BASE_PATH_UI: /siwf/ui
          BASE_PATH_EXAMPLE: /siwf/example
        run: pnpm run build

      - name: Structure Root
        run: |
          mkdir siwf/example
          mkdir siwf/ui
          mv ./packages/ui/build/* ./siwf/ui
          mv ./packages/example/build/* ./siwf/example

      # For now, we want to keep deploying v1 to the root
      # Future will swap this to some basic directory page
      - name: Deploy to GitHub Pages Root
        # if: ${{ github.ref == 'refs/heads/v1' }}
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: siwf
          target-folder: /
          clean: true # Future: Don't clean up the release folders
